# Generated by Django 5.2 on 2025-04-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samgym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
