# Generated by Django 5.2.3 on 2025-08-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumbble', '0001_initial'),
    ]

    operations = [
    ]
